# -*- coding: utf-8 -*-
"""Tarea EDA_JorgeAlvarez.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GgfkMnUbvxJ29QjKy-8UuTxmtQDBDZ3t

#**Tarea EDA - Jorge Álvarez**
# **Sección 1: Carga y exploración inicial de los datos**

## 1.1 Carga de Datos

---

**Archivo: paractice_dataset**

**Tamaño: 1000 registros**

**Variables:**

* ##### *Age: Ingreso*
* ##### *Income: Ingreso*|
* ##### *Credit_Score: Puntaje_Credito*
* ##### *Loan_Amount: Monto_Prestamo*
* ##### *Interest_Rate: Tasa_Interes*
"""

# Linkear con Gogle Drive

from google.colab import drive
drive.mount('/content/drive')

# Importamos pandas para la manipulacion, limpieza y análisis inicial de los datos

import pandas as pd

# Importamos el dataset, bajo formato *.csv. Con su cabecera de etiquetas por columna, codificación para aceptar caracteres latinos, y sin la columna index

dataset = pd.read_csv('/content/drive/MyDrive/Curso Estadistica con Python/Notebook del Curso Estadistica/practice_dataset.csv', header = 0, encoding= 'latin-1', index_col = False)

dataset.head()

print (f"columnas actualizadas:")
print(dataset.columns)

# Renombramos las etiquetas de cada columna, traduciéndolas al español

dataset.rename(columns={'Age': 'Edad', 'Income': 'Ingreso', 'Credit_Score': 'Puntaje_Credito', 'Loan_Amount': 'Monto_Deuda', 'Interest_Rate': 'Tasa_Interes'}, inplace=True)

dataset

# Verificamos etiquetas renombradas

print (f"columnas actualizadas:")
print(dataset.columns)

"""# **Sección 1: Carga y exploración inicial de los datos**

## 1.2 Exploración inicial

---

* ##### *Estructura de los datos*
* ##### *Tipo de datos*
* ##### *Existencia de valores nulos*

"""

# Medida del dataset: número de filas y columnas
# Son mil filas, y 5 columnas

dataset.shape

# Tipo de datos y valores nulos por columna
# Todos los datos son 'float64' (números decimales)
# Existen 900 valores 'no nulos' en cada columna, lo que implica 100 valores nulos en c/u.

dataset.info()

# Revisamos las principales medidas del dataset:

# EDAD: Entre 18 y 64 años, media de 41 años, +/- 14 años.
# INGRESO: De 30 mil a 120 mil, media 75 mil, +/- 26 mil. La mitad por debajo de la media
# y solo 25% por encima de 98 mil
# PUNTAJE CREDITO: Va de 300 a 850; la media 583, +/- 156, solo 25% pasan de 720
# MONTO DEUDA: De 5 mil a 50 mil, promedio 27 mil, +/- 13 mil. La mitad bajo el promedio y 25% sobre 50 mil.
# TASA INTERES: Cobran entre 3.4% y 15%, media de 9%, +/- 3.4%, un 25% está sobre la media

dataset.describe()

"""# **Sección 2: Análisis Exploratorio de Datos**

## 2.1	Utiliza estadísticas descriptivas

---

* ##### *Media*
* ##### *Mediana*
* ##### *Rango intercuartil*
* ##### *Etc.*
"""

# EDAD:
#  Media
#  Mediana
#  Moda

print('El valor de la media: ', round(dataset['Edad'].mean(),2))
print('El valor de la mediana: ', round(dataset['Edad'].median(),2))
print('El valor de la moda: ', round(dataset['Edad'].mode(),2))

# INGRESO:
#  Media
#  Mediana
#  Moda

print('El valor de la media: ', round(dataset['Ingreso'].mean(),2))
print('El valor de la mediana: ', round(dataset['Ingreso'].median(),2))
print('El valor de la moda: ', round(dataset['Ingreso'].mode(),2))

# PUNTAJE_CREDITO:
#  Media
#  Mediana
#  Moda

print('El valor de la media: ', round(dataset['Puntaje_Credito'].mean(),2))
print('El valor de la mediana: ', round(dataset['Puntaje_Credito'].median(),2))
print('El valor de la moda: ', round(dataset['Puntaje_Credito'].mode(),2))

# MONTO_DEUDA:
#  Media
#  Mediana
#  Moda

print('El valor de la media: ', round(dataset['Monto_Deuda'].mean(),2))
print('El valor de la mediana: ', round(dataset['Monto_Deuda'].median(),2))
print('El valor de la moda: ', round(dataset['Monto_Deuda'].mode(),2))

# TASA_INTERES:
#  Media
#  Mediana
#  Moda

print('El valor de la media: ', round(dataset['Tasa_Interes'].mean(),2))
print('El valor de la mediana: ', round(dataset['Tasa_Interes'].median(),2))
print('El valor de la moda: ', round(dataset['Tasa_Interes'].mode(),2))

# Debido a la cantidad de valores modales, buscamos el 'Tipo de dato',
# para cada columna, y si existe una 'Llave primaria'

# Únicamente la 'Tasa de Interés' no repite valores y puede ser empleada como 'Llave primaria'

def obtener_categoria(series):
  conteo_unico = series.nunique(dropna = True)
  conteo_total = series.notna().sum()

  if conteo_unico == conteo_total:
    return 'Llave Primaria'

  elif pd.api.types.is_numeric_dtype(series):
    return 'Cuantitativo'

  elif pd.api.types.is_datetime64_any_dtype(series):
    return 'Fecha'

  else:
    return 'Cualitativo'


def print_categorias(datos):
  for columna in datos.columns:
    print(f'{columna}: {obtener_categoria(dataset[columna])}')

print_categorias(dataset)

# EDAD:
#  Varianza
#  Desviacion Estandar

print('El valor de la varianza: ', round(dataset['Edad'].var(),2))
print('El valor de la desviacion estandar: ', round(dataset['Edad'].std(),2))

# INGRESO:
#  Varianza
#  Desviacion Estandar

print('El valor de la varianza: ', round(dataset['Ingreso'].var(),2))
print('El valor de la desviacion estandar: ', round(dataset['Ingreso'].std(),2))

# PUNTAJE_CREDITO:
#  Varianza
#  Desviacion Estandar

print('El valor de la varianza: ', round(dataset['Puntaje_Credito'].var(),2))
print('El valor de la desviacion estandar: ', round(dataset['Puntaje_Credito'].std(),2))

# MONTO_DEUDA:
#  Varianza
#  Desviacion Estandar

print('El valor de la varianza: ', round(dataset['Monto_Deuda'].var(),2))
print('El valor de la desviacion estandar: ', round(dataset['Monto_Deuda'].std(),2))

# TASA_INTERES:
#  Varianza
#  Desviacion Estandar

print('El valor de la varianza: ', round(dataset['Tasa_Interes'].var(),2))
print('El valor de la desviacion estandar: ', round(dataset['Tasa_Interes'].std(),2))

# EDAD:
#  Minimo
#  Maximo
#  Rango

print('El valor del minimo: ', dataset['Edad'].min())
print('El valor del maximo: ', dataset['Edad'].max())
print('El valor del rango: ', dataset['Edad'].max() - dataset['Edad'].min())

# INGRESO:
#  Minimo
#  Maximo
#  Rango

print('El valor del minimo: ', dataset['Ingreso'].min())
print('El valor del maximo: ', dataset['Ingreso'].max())
print('El valor del rango: ', dataset['Ingreso'].max() - dataset['Ingreso'].min())

# PUNTAJE_CREDITO:
#  Minimo
#  Maximo
#  Rango

print('El valor del minimo: ', dataset['Puntaje_Credito'].min())
print('El valor del maximo: ', dataset['Puntaje_Credito'].max())
print('El valor del rango: ', dataset['Puntaje_Credito'].max() - dataset['Puntaje_Credito'].min())

# MONTO_DEUDA:
#  Minimo
#  Maximo
#  Rango

print('El valor del minimo: ', dataset['Monto_Deuda'].min())
print('El valor del maximo: ', dataset['Monto_Deuda'].max())
print('El valor del rango: ', dataset['Monto_Deuda'].max() - dataset['Monto_Deuda'].min())

# TASA_INTERES:
#  Minimo
#  Maximo
#  Rango

print('El valor del minimo: ', round(dataset['Tasa_Interes'].min(),2))
print('El valor del maximo: ', round(dataset['Tasa_Interes'].max(),2))
print('El valor del rango: ', round(dataset['Tasa_Interes'].max() - dataset['Tasa_Interes'].min(),2))

# EDAD:
#  Cuartiles
#  Quintil
#  Decil
#  Percentil

print('El valor del primer cuartil: ', dataset['Edad'].quantile(0.25))
print('El valor del cuarto quintil: ', round(dataset['Edad'].quantile(0.8),2))
print('El valor del decil 7: ', dataset['Edad'].quantile(0.7))
print('El valor del percentil 60: ', dataset['Edad'].quantile(0.60))

# INGRESO:
#  Cuartiles
#  Quintil
#  Decil
#  Percentil

print('El valor del primer cuartil: ', dataset['Ingreso'].quantile(0.25))
print('El valor del cuarto quintil: ', round(dataset['Ingreso'].quantile(0.8),2))
print('El valor del decil 7: ', round(dataset['Ingreso'].quantile(0.7),2))
print('El valor del percentil 60: ', dataset['Ingreso'].quantile(0.60))

# PUNTAJE_CREDITO:
#  Cuartiles
#  Quintil
#  Decil
#  Percentil

print('El valor del primer cuartil: ', dataset['Puntaje_Credito'].quantile(0.25))
print('El valor del cuarto quintil: ', round(dataset['Puntaje_Credito'].quantile(0.8),2))
print('El valor del decil 7: ', round(dataset['Puntaje_Credito'].quantile(0.7),2))
print('El valor del percentil 60: ', dataset['Puntaje_Credito'].quantile(0.60))

# MONTO_DEUDA:
#  Cuartiles
#  Quintil
#  Decil
#  Percentil

print('El valor del primer cuartil: ', dataset['Monto_Deuda'].quantile(0.25))
print('El valor del cuarto quintil: ', round(dataset['Monto_Deuda'].quantile(0.8),2))
print('El valor del decil 7: ', round(dataset['Monto_Deuda'].quantile(0.7),2))
print('El valor del percentil 60: ', dataset['Monto_Deuda'].quantile(0.60))

# TASA_INTERES:
#  Cuartiles
#  Quintil
#  Decil
#  Percentil

print('El valor del primer cuartil: ', round(dataset['Tasa_Interes'].quantile(0.25),2))
print('El valor del cuarto quintil: ', round(dataset['Tasa_Interes'].quantile(0.8),2))
print('El valor del decil 7: ', round(dataset['Tasa_Interes'].quantile(0.7),2))
print('El valor del percentil 60: ', round(dataset['Tasa_Interes'].quantile(0.60),2))

# Analizamos covarianzas:

#  Edad-Ingreso -> A más edad mayor ingreso y viceversa.
#  Ingreso-Monto_Deuda -> A más Ingreso menor Deuda y viceversa. Alta intensidad.
#  Puntaje_Credito-Monto_Deuda -> A mayor Puntaje de crédito mayor Monto de Deuda y viceversa. Alta intensidad.
#  Tasa_Interes-Ingreso -> A mayor Tasa de interés, mayor Ingreso y viceversa. Con baja intensidad.
#  Tasa interes-Monto_Deuda -> A menor Tasa de Interés, mayor Monto de Deuda y viceversa.

covarianza1 = round(dataset['Edad'].cov(dataset['Ingreso'],2))
print('La covarianza "Edad-Ingreso" es: ', covarianza1)

covarianza2 = round(dataset['Ingreso'].cov(dataset['Monto_Deuda'],2))
print('La covarianza "Ingreso-Monto_Deuda" es: ', covarianza2)

covarianza3 = round(dataset['Puntaje_Credito'].cov(dataset['Monto_Deuda'],2))
print('La covarianza "Puntaje_Credito-Monto_Deuda" es: ', covarianza3)

covarianza4 = round(dataset['Tasa_Interes'].cov(dataset['Ingreso'],2))
print('La covarianza "Tasa_Interes-Ingreso" es: ', covarianza4)

covarianza5 = round(dataset['Tasa_Interes'].cov(dataset['Monto_Deuda'],2))
print('La covarianza "Tasa interes-Monto_Deuda" es: ', covarianza5)

# Revisamos "La matriz de covarianzas":

cov_matrix = round(dataset.cov(numeric_only= True),2)

print('La covarianza es: \n', cov_matrix)

"""# **Sección 2: Análisis Exploratorio de Datos**

## 2.2.	Generamos gráficos  

---

* ##### *2.2.1 Histograma de las 5 variables*
* ##### *2.2.2 Mapa de calor de las 5 variables*
* ##### *2.2.3 Gráfico de Dispersión de los principales pares de variables*
* ##### *2.2.4 Pairplot completo para identificar clusters en variables numéricas*
"""

# Cargamos librerías para graficar

import pandas as pd
import numpy as np

#Graficos
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib import style

#Configurar los Estilos de los graficos
plt.style.use('ggplot')

#Preprocesado y analisis
from scipy import stats
import statsmodels.api as sm

#Configuramos los errores o advertencias
import warnings
warnings.filterwarnings('ignore')

dataset.head()

"""# **Sección 2: Análisis Exploratorio de Datos**

## 2.2.	Realiza gráficos  

---

* ##### *2.2.1 Histograma de las 5 variables*

"""

#Empleamos la 'Formula de Sturges' para definir el número de "bins" (columnas) en el histograma

import math

def sturges_formula(n):
  k = 1 +3.32 * math.log10(n)
  return round(k)

n = 900 # reemplazar con la cantidad de filas del set de datos
num_bins = sturges_formula(n)
print('Numero de bines segun la formula de Sturges es: ', num_bins)

## EDAD: -> No se aprecia 'distribución normal' de los datoa.
## Histograma + curva normal teorica

#Valores de la media (mu) y desviacion estandar (sigma) de los datos

mu, sigma = stats.norm.fit(dataset['Edad'].dropna())

#Valores Teorico de la normaliadd del rango observado
x_hat = np.linspace(min(dataset['Edad'].dropna()), max(dataset['Edad'].dropna()), num = 900)
y_hat = stats.norm.pdf(x_hat, mu , sigma)

#Grafico
fig, ax = plt.subplots(figsize = (7,4))
ax.plot(x_hat, y_hat , linewidth = 2, label = 'normal')
ax.hist(x = dataset['Edad'].dropna(), density= True, bins=num_bins, alpha = 0.5)
ax.plot(dataset['Edad'].dropna(),np.full_like(dataset['Edad'].dropna(),-0.01),'|k',markeredgewidth = 1)
ax.set_title('Distribucion Edad')
ax.set_xlabel('Edad')
ax.set_ylabel('Densidad de Probabilidad')
#ax.annotate('mu', [60,0.08])
ax.legend()
plt.show()

## INGRESO: -> No se aprecia 'distribución normal' de los datoa.
## Histograma + curva normal teórica

# Valores de la media (mu) y desviación estándar (sigma) de los datos
mu, sigma = stats.norm.fit(dataset['Ingreso'].dropna())

# Valores teóricos de la normalidad del rango observado
x_hat = np.linspace(min(dataset['Ingreso'].dropna()), max(dataset['Ingreso'].dropna()), num=900)

# Escalar la curva normal al número de observaciones
n = len(dataset['Ingreso'].dropna())
bin_width = (max(dataset['Ingreso'].dropna()) - min(dataset['Ingreso'].dropna())) / num_bins
y_hat = stats.norm.pdf(x_hat, mu, sigma) * n * bin_width

# Gráfico
fig, ax = plt.subplots(figsize=(7,4))
ax.plot(x_hat, y_hat, linewidth=2, label='normal')
ax.hist(x=dataset['Ingreso'].dropna(), density=False, bins=num_bins, alpha=0.5)
ax.plot(dataset['Ingreso'].dropna(), np.full_like(dataset['Ingreso'].dropna(), -0.5), '|k', markeredgewidth=1)
ax.set_title('Distribución Ingreso')
ax.set_xlabel('Ingreso')
ax.set_ylabel('Frecuencia')
ax.legend()
plt.show()

## PUNTAJE_CREDITO: -> No se aprecia 'distribución normal' de los datoa.
## Histograma + curva normal teórica

# Valores de la media (mu) y desviación estándar (sigma) de los datos
mu, sigma = stats.norm.fit(dataset['Puntaje_Credito'].dropna())

# Valores teóricos de la normalidad del rango observado
x_hat = np.linspace(min(dataset['Puntaje_Credito'].dropna()), max(dataset['Puntaje_Credito'].dropna()), num=900)

# Escalar la curva normal al número de observaciones
n = len(dataset['Puntaje_Credito'].dropna())
bin_width = (max(dataset['Puntaje_Credito'].dropna()) - min(dataset['Puntaje_Credito'].dropna())) / num_bins
y_hat = stats.norm.pdf(x_hat, mu, sigma) * n * bin_width

# Gráfico
fig, ax = plt.subplots(figsize=(7,4))
ax.plot(x_hat, y_hat, linewidth=2, label='normal')
ax.hist(x=dataset['Puntaje_Credito'].dropna(), density=False, bins=num_bins, alpha=0.5)
ax.plot(dataset['Puntaje_Credito'].dropna(), np.full_like(dataset['Puntaje_Credito'].dropna(), -0.5), '|k', markeredgewidth=1)
ax.set_title('Distribución Puntaje de Crédito')
ax.set_xlabel('Puntaje de Crédito')
ax.set_ylabel('Frecuencia')
ax.legend()
plt.show()

## MONTO_DEUDA: -> No se aprecia 'distribución normal' de los datoa.
## Histograma + curva normal teórica

# Valores de la media (mu) y desviación estándar (sigma) de los datos
mu, sigma = stats.norm.fit(dataset['Monto_Deuda'].dropna())

# Valores teóricos de la normalidad del rango observado
x_hat = np.linspace(min(dataset['Monto_Deuda'].dropna()), max(dataset['Monto_Deuda'].dropna()), num=900)

# Escalar la curva normal al número de observaciones
n = len(dataset['Monto_Deuda'].dropna())
bin_width = (max(dataset['Monto_Deuda'].dropna()) - min(dataset['Monto_Deuda'].dropna())) / num_bins
y_hat = stats.norm.pdf(x_hat, mu, sigma) * n * bin_width

# Gráfico
fig, ax = plt.subplots(figsize=(7,4))
ax.plot(x_hat, y_hat, linewidth=2, label='normal')
ax.hist(x=dataset['Monto_Deuda'].dropna(), density=False, bins=num_bins, alpha=0.5)
ax.plot(dataset['Monto_Deuda'].dropna(), np.full_like(dataset['Monto_Deuda'].dropna(), -0.5), '|k', markeredgewidth=1)
ax.set_title('Distribución Monto de Deuda')
ax.set_xlabel('Monto de Deuda')
ax.set_ylabel('Frecuencia')
ax.legend()
plt.show()

## TASA_INTERES: -> No se aprecia 'distribución normal' de los datoa.
## Histograma + curva normal teórica

# Valores de la media (mu) y desviación estándar (sigma) de los datos
mu, sigma = stats.norm.fit(dataset['Tasa_Interes'].dropna())

# Valores teóricos de la normalidad del rango observado
x_hat = np.linspace(min(dataset['Tasa_Interes'].dropna()), max(dataset['Tasa_Interes'].dropna()), num=900)

# Escalar la curva normal al número de observaciones
n = len(dataset['Tasa_Interes'].dropna())
bin_width = (max(dataset['Tasa_Interes'].dropna()) - min(dataset['Tasa_Interes'].dropna())) / num_bins
y_hat = stats.norm.pdf(x_hat, mu, sigma) * n * bin_width

# Gráfico
fig, ax = plt.subplots(figsize=(7,4))
ax.plot(x_hat, y_hat, linewidth=2, label='normal')
ax.hist(x=dataset['Tasa_Interes'].dropna(), density=False, bins=num_bins, alpha=0.5)
ax.plot(dataset['Tasa_Interes'].dropna(), np.full_like(dataset['Tasa_Interes'].dropna(), -0.5), '|k', markeredgewidth=1)
ax.set_title('Distribución Tasa de Interés')
ax.set_xlabel('Tasa de Interés (%)')
ax.set_ylabel('Frecuencia')
ax.legend()
plt.show()

"""# **Sección 2: Análisis Exploratorio de Datos**

## 2.2.	Realiza gráficos  

---

* ##### *2.2.2 Mapa de calor de las 5 variables*

"""

# Importar las librerias

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Matriz de Correlación

corr = dataset.corr(numeric_only=True)

corr

# Generamos la gráfica del 'Mapa de calor'  -> No se aprecia 'niveles de correlación importantes' entre las variables.

fig, ax  =  plt.subplots(figsize = (10,6))
sns.heatmap(corr, annot = True,cmap = 'YlGnBu', ax = ax, vmax = 1, vmin = -1)
plt.title('Matriz de Correlacion')
plt.show()

"""# **Sección 2: Análisis Exploratorio de Datos**

## 2.2.	Realiza gráficos  

---

* ##### *2.2.3 Gráfico de Dispersión de los principales pares de variables*
"""

# Graficamos la Relación entre Puntaje_Credito y Tasa_Interes

plt.figure(figsize= (12, 6))
sns.scatterplot(data = dataset, x = 'Puntaje_Credito', y  = 'Tasa_Interes', alpha = 0.7 )

#Configuracion de las etiquetas y el titulo
plt.xlabel('Puntaje_Credito')
plt.ylabel('Tasa_Interes')
plt.title('Relación entre Puntaje_Credito y Tasa_Interes', fontsize = 14, fontweight = 'bold')
plt.grid(True)

plt.show()

# Graficamos la Relación entre Edad y Monto_Deuda

plt.figure(figsize= (12, 6))
sns.scatterplot(data = dataset, x = 'Edad', y  = 'Monto_Deuda', alpha = 0.7 )

#Configuracion de las etiquetas y el titulo
plt.xlabel('Edad')
plt.ylabel('Monto_Deuda')
plt.title('Relación entre Edad y Monto_Deuda', fontsize = 14, fontweight = 'bold')
plt.grid(True)

plt.show()

# Graficamos la Relación entre Ingreso y Monto_Deuda

plt.figure(figsize= (12, 6))
sns.scatterplot(data = dataset, x = 'Ingreso', y  = 'Monto_Deuda', alpha = 0.7 )

#Configuracion de las etiquetas y el titulo
plt.xlabel('Ingreso')
plt.ylabel('Monto_Deuda')
plt.title('Relación entre Ingreso y Monto_Deuda', fontsize = 14, fontweight = 'bold')
plt.grid(True)

plt.show()

# Graficamos la Relación entre Tasa_Interes y Monto_Deuda

plt.figure(figsize= (12, 6))
sns.scatterplot(data = dataset, x = 'Tasa_Interes', y  = 'Monto_Deuda', alpha = 0.7 )

#Configuracion de las etiquetas y el titulo
plt.xlabel('Tasa_Interes')
plt.ylabel('Monto_Deuda')
plt.title('Relación entre Tasa_Interes y Monto_Deuda', fontsize = 14, fontweight = 'bold')
plt.grid(True)

plt.show()

"""# **Sección 2: Análisis Exploratorio de Datos**

## 2.2.	Realiza gráficos  

---

* ##### *2.2.4.1 Pairplot_1 completo para identificar clusters en variables numéricas*
"""

# Graficamos un Pairplot para identificar clusters en variables numéricas.
# Porque la distribución de datos no muestra normalidad. Entonces tratamos de buscar algún tipo de asociación tipo cluster.
# Tampoco se aprecia relación entre si,dentro de la distribución de los datos.

import seaborn as sns
import matplotlib.pyplot as plt

# Eliminar filas con valores nulos para el pairplot
dataset_cleaned = dataset.dropna()

# Generar el pairplot
sns.pairplot(dataset_cleaned)
plt.suptitle('Pairplot para identificar clusters en variables numéricas', y=1.02)
plt.show()

"""# **Sección 2: Análisis Exploratorio de Datos**

## 2.2.	Realiza gráficos  

---

* ##### *2.2.4.2 Pairplot_2 tipo 'kde', para análisis cualitativo (forma/tendencia), y para identificar si hay múltiples "picos" en los datos*
"""

# Graficamos un pairplot tipo 'kde' para buscar forma, tendencia y eventuales 'picos' en la data.

# Generar una gráfica estadística con variables numéricas
# Solo se aprecia una curva de diistribución normal cuando las variables se cruzan contra si mismas.
# La interacción con variables diferentes no muestra un patrón definido.

sns.pairplot(dataset, diag_kind='kde')

plt.show()

"""# **Sección 2: Análisis Exploratorio de Datos**

## 2.2.	Realiza gráficos  

---

* ##### *2.2.4.3 Pairplot_3 pairplot con hue. Con segmentación por categorías para el Monto_Deuda: Alta, Media, Baja*
"""

# Graficamos un pairplot de tipo 'hue', que segmenta la Edad en: Joven, Adulto, Mayor.

# Crear categorías de edad
dataset['Categoria_Edad'] = pd.cut(dataset['Edad'],
                                    bins=3,
                                    labels=['Joven', 'Adulto', 'Mayor'])

# Pairplot coloreado por categoría
sns.pairplot(dataset, hue='Categoria_Edad', diag_kind='kde')

plt.show()

# Graficamos un pairplot de tipo 'hue', que segmenta el Ingreso en: Bajo, Medio, Alto.

# Crear categorías de ingreso
dataset['Categoria_Ingreso'] = pd.cut(dataset['Ingreso'],
                                       bins=3,
                                       labels=['Bajo', 'Medio', 'Alto'])

# Pairplot coloreado por categoría
sns.pairplot(dataset, hue='Categoria_Ingreso', diag_kind='kde')

plt.show()

# Graficamos un pairplot de tipo 'hue', que segmenta el Puntaje de Crédito en: Bajo, Medio, Alto.

# Crear categorías de puntaje de crédito
dataset['Categoria_Puntaje_Credito'] = pd.cut(dataset['Puntaje_Credito'],
                                       bins=3,
                                       labels=['Bajo', 'Medio', 'Alto'])

# Pairplot coloreado por categoría
sns.pairplot(dataset, hue='Categoria_Puntaje_Credito', diag_kind='kde')

plt.show()

# Graficamos un pairplot de tipo 'hue', que segmenta el Monto de la Deuda en: Alta, Media, Baja.

# Crear categorías de deuda
dataset['Categoria_Deuda'] = pd.cut(dataset['Monto_Deuda'],
                                     bins=3,
                                     labels=['Baja', 'Media', 'Alta'])

# Pairplot coloreado por categoría
sns.pairplot(dataset, hue='Categoria_Deuda', diag_kind='kde')

plt.show()

# Graficamos un pairplot de tipo 'hue', que segmenta la Tasa de Interés en: Baja, Media, Alta.

# Crear categorías de tasa de interés
dataset['Categoria_Tasa_Interes'] = pd.cut(dataset['Tasa_Interes'],
                                    bins=3,
                                    labels=['Baja', 'Media', 'Alta'])

# Pairplot coloreado por categoría
sns.pairplot(dataset, hue='Categoria_Tasa_Interes', diag_kind='kde')

plt.show()

"""# **Sección 3: Detección de Valores Atípicos**

## 3.1	Método Univariante   

---

3.1.1 *Metodo del Rango Intercuartilico*

3.1.2 *Distribución de Valores atípicos IQR*

[Nota: No se aplica la técnica de "Puntuación Z" debido a que no se aprecia normalidad en la distribución de los datos]

## 3.2	Método Multivariante

---

3.2.1 Bosque de Aislamiento

3.2.2 DBSCAN

3.2.3 Fator Atípico Local  (LOF)

# **Sección 3: Detección de Valores Atípicos**

## 3.1	Método Univariante   

---

3.1.1 *Metodo del Rango Intercuartilico*
"""

# Boxplot para ver valores atipicos; Edad:

plt.figure(figsize=(4, 6))
sns.boxplot(y = dataset['Edad'])
plt.title('Boxplot Edad')
plt.show()

# Boxplot para ver valores atipicos; Ingreso:

plt.figure(figsize=(4, 6))
sns.boxplot(y = dataset['Ingreso'])
plt.title('Boxplot Ingreso')
plt.show()

# Boxplot para ver valores atipicos; Puntaje_Credito:

plt.figure(figsize=(4, 6))
sns.boxplot(y = dataset['Puntaje_Credito'])
plt.title('Boxplot Puntaje_Credito')
plt.show()



# Boxplot para ver valores atipicos; Monto_Deuda

plt.figure(figsize=(4, 6))
sns.boxplot(y = dataset['Monto_Deuda'])
plt.title('Boxplot Monto_Deuda')
plt.show()

# Boxplot para ver valores atipicos; Tasa_Interes:

plt.figure(figsize=(4, 6))
sns.boxplot(y = dataset['Tasa_Interes'])
plt.title('Boxplot Tasa_Interes')
plt.show()

"""# **Sección 3: Detección de Valores Atípicos**

## 3.1	Método Univariante   

---

3.1.2 *Distribución de Valores atípicos IQR*
"""

# DETECCIÖN DE OUTLIERS: Límite Inferior y Superior

def fuera_rango_iqr(data, columna, factor = 1.5):
  Q1 = np.quantile(data[columna], 0.25)
  Q3 = np.quantile(data[columna], 0.75)
  IQR = Q3 - Q1
  lim_inf = Q1 - factor * IQR
  lim_sup = Q3 + factor * IQR

  df1 = data[data[columna]  > lim_sup]
  df2 = data[data[columna]  < lim_inf]

  print(f"[{columna}] IQR:  {IQR:.2f}  | Inferior: {lim_inf:.2f} | Superior: {lim_sup:.2f}")
  print(f"[{columna}] Valores atípicos detectados: {df1.shape[0] + df2.shape[0]}")

  return lim_inf, lim_sup

# VISUALIZACIÓN

def graficar_outliers_iqr(data, columna, lim_inf, lim_sup):
    """
    Gráfico de Histograma con zonas de valores atípicos según el método del IQR
    """

    plt.figure(figsize=(10, 6))

    # Histograma con KDE para distribución
    sns.histplot(data[columna], kde=True, bins=11, color='skyblue')

    # Mediana
    mediana = data[columna].median()
    plt.axvline(x=mediana, color='blue', linestyle='dashed', linewidth=1, label='Mediana')

    # Límite IQR
    plt.axvline(x=lim_inf, color='red', linestyle='dashed', linewidth=1, label="Límite Inferior")
    plt.axvline(x=lim_sup, color='red', linestyle='dashed', linewidth=1, label="Límite Superior")

    # Áreas rojas de outliers
    if data[columna].min() < lim_inf:
        plt.axvspan(data[columna].min(), lim_inf, color='red', alpha=0.2)
    if data[columna].max() > lim_sup:
        plt.axvspan(lim_sup, data[columna].max(), color='red', alpha=0.2)

    # Título y Leyenda
    plt.title(f'Distribución con valores atípicos (IQR) en {columna}')
    plt.legend(fontsize=10, loc='upper left', frameon=True, fancybox=True, framealpha=0.5)
    plt.xlabel(columna)
    plt.ylabel('Frecuencia')
    plt.show()

# Calcular los límites IQR para Edad

Q1 = dataset['Edad'].quantile(0.25)
Q3 = dataset['Edad'].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Llamar a la función para ver la gráfica
graficar_outliers_iqr(dataset, 'Edad', limite_inferior, limite_superior)

# Calcular los límites IQR para Ingreso

Q1 = dataset['Ingreso'].quantile(0.25)
Q3 = dataset['Ingreso'].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Ahora sí llamar a la función para ver la gráfica
graficar_outliers_iqr(dataset, 'Ingreso', limite_inferior, limite_superior)

# Calcular los límites IQR para Puntaje_Credito

Q1 = dataset['Puntaje_Credito'].quantile(0.25)
Q3 = dataset['Puntaje_Credito'].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Llamar a la función para ver la gráfica
graficar_outliers_iqr(dataset, 'Puntaje_Credito', limite_inferior, limite_superior)

# Calcular los límites IQR para Monto_Deuda

Q1 = dataset['Monto_Deuda'].quantile(0.25)
Q3 = dataset['Monto_Deuda'].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Llamar a la función para ver la gráfica
graficar_outliers_iqr(dataset, 'Monto_Deuda', limite_inferior, limite_superior)

# Calcular los límites IQR para Tasa_Interes

Q1 = dataset['Tasa_Interes'].quantile(0.25)
Q3 = dataset['Tasa_Interes'].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

# Llamar a la función para ver la gráfica
graficar_outliers_iqr(dataset, 'Tasa_Interes', limite_inferior, limite_superior)

"""# **Sección 3: Detección de Valores Atípicos**

## 3.2	Método Multivariante   

---

3.2.1 *Metodo del Bosque de Aislamiento*

"""

# Traducir etiquetas de columnas al español

dataset = dataset.rename(columns={
    'Age': 'Edad',
    'Income': 'Ingreso',
    'Credit_Score': 'Puntaje_Credito',
    'Loan_Amount': 'Monto_Deuda',
    'Interest_Rate': 'Tasa_Interes'
})

# ====================================================================
# SCRIPT COMPLETO: DETECCIÓN DE OUTLIERS CON ISOLATION FOREST
# ====================================================================

# 1. IMPORTAR LIBRERÍAS
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import IsolationForest
from scipy import stats

# 2. CARGAR DATASET
dataset = pd.read_csv('/content/drive/MyDrive/Curso Estadistica con Python/Notebook del Curso Estadistica/practice_dataset.csv', header=0, index_col=False)

# TRADUCIR COLUMNAS AL ESPAÑOL
dataset = dataset.rename(columns={
    'Age': 'Edad',
    'Income': 'Ingreso',
    'Credit_Score': 'Puntaje_Credito',
    'Loan_Amount': 'Monto_Deuda',
    'Interest_Rate': 'Tasa_Interes'
})

print("Columnas traducidas correctamente:")
print(dataset.columns.tolist())

# ====================================================================
# 3. DEFINIR FUNCIONES
# ====================================================================

def detectar_outliers_isolation_univariante(data, columnas, contamination=0.1):
    """
    Detecta outliers usando Isolation Forest para cada columna individualmente

    Parámetros:
    - data: DataFrame
    - columnas: lista de nombres de columnas a analizar
    - contamination: proporción esperada de outliers (default 0.1 = 10%)

    Retorna:
    - DataFrame con columnas adicionales: {columna}_outlier y {columna}_score
    """
    df_result = data.copy()

    if isinstance(columnas, str):
        columnas = [columnas]

    for col in columnas:
        if col not in df_result.columns:
            print(f"Advertencia: La columna '{col}' no existe en el dataset")
            continue

        # Preparar datos (eliminar NaN)
        datos = df_result[[col]].dropna()

        if len(datos) == 0:
            print(f"Advertencia: La columna '{col}' no tiene datos válidos")
            continue

        # Crear y entrenar modelo
        modelo = IsolationForest(contamination=contamination, random_state=42)
        predicciones = modelo.fit_predict(datos)
        scores = modelo.score_samples(datos)

        # Agregar resultados al dataset (inicializar con NaN)
        df_result[f'{col}_outlier'] = np.nan
        df_result[f'{col}_score'] = np.nan

        # Asignar valores solo a las filas sin NaN
        df_result.loc[datos.index, f'{col}_outlier'] = predicciones
        df_result.loc[datos.index, f'{col}_score'] = scores

        # Contar outliers
        n_outliers = (predicciones == -1).sum()
        n_normal = (predicciones == 1).sum()
        print(f"[{col}] Normales: {n_normal}, Outliers: {n_outliers}")

    return df_result


def graficar_isolation_univariante(dataset, columnas):
    """
    Visualiza los outliers detectados por Isolation Forest con un gráfico de puntos,
    resaltando los valores atípicos de otro color
    """
    if isinstance(columnas, str):
        columnas = [columnas]

    for col in columnas:
        score_col = f"{col}_score"
        outlier_col = f"{col}_outlier"

        if score_col not in dataset.columns or outlier_col not in dataset.columns:
            print(f"[{col}] no tiene columnas auxiliares generadas por Isolation Forest")
            continue

        # FILTRAR SOLO FILAS SIN NaN
        datos_validos = dataset[[col, score_col, outlier_col]].dropna()

        if len(datos_validos) == 0:
            print(f"[{col}] no tiene datos válidos para graficar")
            continue

        plt.figure(figsize=(10, 6))

        # Mapear colores solo para datos válidos
        colores = datos_validos[outlier_col].map({1: 'skyblue', -1: "red"})

        # Scatter: Valores en X, puntuación en Y
        plt.scatter(datos_validos[col], datos_validos[score_col],
                    c=colores, s=40, edgecolors="black", alpha=0.7)

        plt.title(f'Puntuación anómala vs valor real - {col}')
        plt.xlabel(f"{col}")
        plt.ylabel('Puntuación anómala (score)')
        plt.tight_layout()
        plt.show()


def filtrar_outliers_isolation_univariante(data, columnas, conservar_columnas_aux=False):
    """
    Filtra (elimina) las filas que contienen outliers en cualquiera de las columnas especificadas

    Parámetros:
    - data: DataFrame con columnas {columna}_outlier
    - columnas: lista de columnas evaluadas
    - conservar_columnas_aux: si True, mantiene las columnas *_outlier y *_score

    Retorna:
    - DataFrame filtrado sin outliers
    """
    df_filtrado = data.copy()

    if isinstance(columnas, str):
        columnas = [columnas]

    # Crear máscara para filtrar
    mascara_outliers = pd.Series([False] * len(df_filtrado), index=df_filtrado.index)

    for col in columnas:
        outlier_col = f"{col}_outlier"

        if outlier_col not in df_filtrado.columns:
            print(f"Advertencia: No existe la columna '{outlier_col}'")
            continue

        # Marcar filas con outliers (-1)
        mascara_outliers = mascara_outliers | (df_filtrado[outlier_col] == -1)

    # Filtrar filas
    n_antes = len(df_filtrado)
    df_filtrado = df_filtrado[~mascara_outliers]
    n_despues = len(df_filtrado)
    n_eliminados = n_antes - n_despues

    print(f"\nFilas eliminadas: {n_eliminados} ({n_eliminados/n_antes*100:.2f}%)")
    print(f"Filas restantes: {n_despues}")

    # Eliminar columnas auxiliares si se solicita
    if not conservar_columnas_aux:
        columnas_aux = [f"{col}_outlier" for col in columnas] + [f"{col}_score" for col in columnas]
        columnas_aux_existentes = [c for c in columnas_aux if c in df_filtrado.columns]
        df_filtrado = df_filtrado.drop(columns=columnas_aux_existentes)
        print(f"Columnas auxiliares eliminadas: {len(columnas_aux_existentes)}")

    return df_filtrado


def graficar_outliers_iqr(data, columna, lim_inf, lim_sup):
    """
    Gráfico de Histograma con zonas de valores atípicos según el método del IQR
    """
    plt.figure(figsize=(10, 6))

    # Histograma con KDE para distribución
    sns.histplot(data[columna], kde=True, bins=11, color='skyblue')

    # Mediana
    mediana = data[columna].median()
    plt.axvline(x=mediana, color='blue', linestyle='dashed', linewidth=1, label='Mediana')

    # Límite IQR
    plt.axvline(x=lim_inf, color='red', linestyle='dashed', linewidth=1, label="Límite Inferior")
    plt.axvline(x=lim_sup, color='red', linestyle='dashed', linewidth=1, label="Límite Superior")

    # Áreas rojas de outliers
    if data[columna].min() < lim_inf:
        plt.axvspan(data[columna].min(), lim_inf, color='red', alpha=0.2)
    if data[columna].max() > lim_sup:
        plt.axvspan(lim_sup, data[columna].max(), color='red', alpha=0.2)

    # Título y Leyenda
    plt.title(f'Distribución con valores atípicos (IQR) en {columna}')
    plt.legend(fontsize=10, loc='upper left', frameon=True, fancybox=True, framealpha=0.5)
    plt.xlabel(columna)
    plt.ylabel('Frecuencia')
    plt.show()


# ====================================================================
# 4. ANÁLISIS EXPLORATORIO DE DATOS (EDA)
# ====================================================================

print("\n" + "=" * 60)
print("INFORMACIÓN DEL DATASET")
print("=" * 60)
print(dataset.info())
print("\n")
print(dataset.describe())

# ====================================================================
# 5. DETECCIÓN DE OUTLIERS CON ISOLATION FOREST
# ====================================================================

print("\n" + "=" * 60)
print("DETECCIÓN DE OUTLIERS CON ISOLATION FOREST")
print("=" * 60)

# Definir columnas a analizar
columnas_numericas = ['Edad', 'Ingreso', 'Puntaje_Credito', 'Monto_Deuda', 'Tasa_Interes']

# Detectar outliers
df_con_outliers = detectar_outliers_isolation_univariante(
    dataset,
    columnas_numericas,
    contamination=0.05  # 5% de outliers esperados
)

# Visualizar outliers
print("\nGenerando gráficos de outliers...")
graficar_isolation_univariante(df_con_outliers, columnas_numericas)

# Filtrar outliers
dataset_limpio = filtrar_outliers_isolation_univariante(
    df_con_outliers,
    columnas_numericas,
    conservar_columnas_aux=False
)

# ====================================================================
# 6. DETECCIÓN DE OUTLIERS CON MÉTODO IQR (OPCIONAL)
# ====================================================================

print("\n" + "=" * 60)
print("DETECCIÓN DE OUTLIERS CON MÉTODO IQR")
print("=" * 60)

# Ejemplo para Monto_Deuda
Q1 = dataset['Monto_Deuda'].quantile(0.25)
Q3 = dataset['Monto_Deuda'].quantile(0.75)
IQR = Q3 - Q1
limite_inferior = Q1 - 1.5 * IQR
limite_superior = Q3 + 1.5 * IQR

print(f"\nMonto_Deuda - IQR:")
print(f"Q1: {Q1:.2f}, Q3: {Q3:.2f}, IQR: {IQR:.2f}")
print(f"Límite inferior: {limite_inferior:.2f}")
print(f"Límite superior: {limite_superior:.2f}")

graficar_outliers_iqr(dataset, 'Monto_Deuda', limite_inferior, limite_superior)

# ====================================================================
# 7. VISUALIZACIONES ADICIONALES
# ====================================================================

print("\n" + "=" * 60)
print("VISUALIZACIONES ADICIONALES")
print("=" * 60)

# Matriz de correlación
print("\nGenerando matriz de correlación...")
corr = dataset_limpio.corr(numeric_only=True)

plt.figure(figsize=(10, 8))
sns.heatmap(corr, annot=True, cmap='coolwarm', center=0, fmt='.2f')
plt.title('Matriz de Correlación (Dataset Limpio)')
plt.tight_layout()
plt.show()

# Pairplot simple
print("\nGenerando pairplot...")
sns.pairplot(dataset_limpio, diag_kind='kde')
plt.show()

# Pairplot con categorías de Ingreso
print("\nGenerando pairplot con categorías de Ingreso...")
dataset_limpio['Categoria_Ingreso'] = pd.cut(
    dataset_limpio['Ingreso'],
    bins=3,
    labels=['Bajo', 'Medio', 'Alto']
)
sns.pairplot(dataset_limpio, hue='Categoria_Ingreso', diag_kind='kde')
plt.show()

print("\n" + "=" * 60)
print("ANÁLISIS COMPLETADO")
print("=" * 60)
print(f"\nDataset original: {len(dataset)} filas")
print(f"Dataset limpio: {len(dataset_limpio)} filas")
print(f"Outliers eliminados: {len(dataset) - len(dataset_limpio)} filas")

"""# **Sección 3: Detección de Valores Atípicos**

## 3.2	Método Multivariante   

---

3.2.2 *Metodo DBSCAN*

"""

# BUscamos DETECTAR los outliers, con el Método DBSCAN

from sklearn.cluster import DBSCAN
from sklearn.preprocessing import StandardScaler

def detectar_outlier_dbscan(dataset, columnas, epsilon=0.5, min_samples=5):
    """
    Detecta outliers utilizando el algoritmo DBSCAN

    Parámetros:
    - dataset: DataFrame
    - columnas: lista de columnas a analizar
    - epsilon: distancia máxima entre puntos (eps)
    - min_samples: número mínimo de puntos para formar un cluster

    Retorna:
    - DataFrame con columna 'cluster' (-1 = outlier, >=0 = cluster)
    """
    df_resultado = dataset.copy()

    # Eliminar filas con NaN en las columnas especificadas
    datos_validos = df_resultado[columnas].dropna()

    # Escalar las variables
    X = datos_validos.values
    x_scaled = StandardScaler().fit_transform(X)

    # Aplicar DBSCAN
    dbscan = DBSCAN(eps=epsilon, min_samples=min_samples).fit(x_scaled)
    etiquetas = dbscan.labels_  # -1 = outlier, 0 o más = cluster

    # Asignar clusters (inicializar con NaN)
    df_resultado['cluster'] = np.nan
    df_resultado.loc[datos_validos.index, 'cluster'] = etiquetas

    # Contar outliers y clusters
    n_outliers = (etiquetas == -1).sum()
    n_clusters = len(set(etiquetas)) - (1 if -1 in etiquetas else 0)
    n_normales = len(etiquetas) - n_outliers

    print(f"Outliers detectados: {n_outliers}")
    print(f"Puntos normales: {n_normales}")
    print(f"Número de clusters: {n_clusters}")

    return df_resultado

# Ahora buscamos GRAFICAR

from sklearn.decomposition import PCA

def graficar_outliers_dbscan(dataset, columnas, etiqueta_col='cluster'):
    """
    Visualizar outliers vs normales con 2 columnas en un espacio de 2 Dimensiones.
    Si hay más de 2 columnas, se aplica un PCA para reducir las dimensiones a 2.
    Los puntos normales se grafican azul y los outliers rojo
    """

    if len(columnas) < 2:
        raise ValueError("El dataset debe tener al menos 2 columnas numéricas para graficar")

    # Filtrar solo filas sin NaN en las columnas relevantes
    columnas_analizar = columnas + [etiqueta_col]
    datos_validos = dataset[columnas_analizar].dropna()

    if len(datos_validos) == 0:
        print("No hay datos válidos para graficar")
        return

    # Reducción con PCA si hay más de 2 columnas
    if len(columnas) > 2:
        print('Aplicando PCA para reducir las dimensiones...')
        X = datos_validos[columnas].values
        X_reducido = PCA(n_components=2, random_state=123).fit_transform(X)
        x_label, y_label = "PCA Componente 1", "PCA Componente 2"
    else:
        X_reducido = datos_validos[columnas].values
        x_label, y_label = columnas[0], columnas[1]

    # Obtener etiquetas de Outliers
    etiquetas = datos_validos[etiqueta_col].values
    normales = etiquetas != -1
    outliers = etiquetas == -1

    # Crear la figura
    plt.figure(figsize=(10, 6))

    # Graficar los puntos normales
    plt.scatter(X_reducido[normales, 0], X_reducido[normales, 1],
                color='blue', label='Puntos Normales',
                edgecolor='black', alpha=0.7, s=60)

    # Graficar los puntos outliers
    plt.scatter(X_reducido[outliers, 0], X_reducido[outliers, 1],
                color='red', label='Puntos Outliers',
                edgecolor='black', alpha=0.7, s=60)

    # Etiquetas y leyenda
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.legend(loc='upper right')
    plt.title('Visualización de Outliers con DBSCAN')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Buscamos ELIMINAR los outliers

def eliminar_outliers_dbscan(dataset, outlier_col='cluster', conservar_columna=False):
    """
    Elimina los outliers detectados por DBSCAN (etiqueta -1)

    Parámetros:
    - dataset: DataFrame con columna de clusters
    - outlier_col: nombre de la columna con etiquetas (default 'cluster')
    - conservar_columna: si True, mantiene la columna de clusters

    Retorna:
    - DataFrame sin outliers
    """
    # Filtrar filas que NO son outliers (-1)
    df_resultado = dataset[dataset[outlier_col] != -1].copy()

    # Eliminar columna de clusters si se solicita
    if not conservar_columna:
        df_resultado = df_resultado.drop(columns=[outlier_col])

    # Estadísticas
    n_eliminados = len(dataset) - len(df_resultado)
    print(f'Filas originales: {len(dataset)}')
    print(f'Outliers eliminados: {n_eliminados}')
    print(f'Filas restantes: {df_resultado.shape[0]}')

    return df_resultado

# Cálculo para determinar el Epsilon adecuado; "Método del Codo"

from sklearn.neighbors import NearestNeighbors

# DIAGNÓSTICO: Encontrar epsilon óptimo
def encontrar_epsilon_optimo(dataset, columnas, k=5):
    """
    Encuentra el epsilon óptimo usando el método del codo (k-distance)
    """
    # Preparar datos
    datos_validos = dataset[columnas].dropna()
    X = datos_validos.values
    x_scaled = StandardScaler().fit_transform(X)

    # Calcular distancias a los k vecinos más cercanos
    vecinos = NearestNeighbors(n_neighbors=k)
    vecinos.fit(x_scaled)
    distancias, indices = vecinos.kneighbors(x_scaled)

    # Ordenar distancias al k-ésimo vecino
    distancias_k = np.sort(distancias[:, k-1], axis=0)

    # Graficar
    plt.figure(figsize=(10, 6))
    plt.plot(distancias_k)
    plt.xlabel('Puntos ordenados')
    plt.ylabel(f'Distancia al {k}-ésimo vecino más cercano')
    plt.title('Método del Codo para encontrar Epsilon óptimo')
    plt.grid(True)
    plt.axhline(y=np.median(distancias_k), color='r', linestyle='--', label=f'Mediana: {np.median(distancias_k):.2f}')
    plt.axhline(y=np.percentile(distancias_k, 95), color='g', linestyle='--', label=f'Percentil 95: {np.percentile(distancias_k, 95):.2f}')
    plt.legend()
    plt.show()

    print(f"\nSugerencias de epsilon:")
    print(f"- Epsilon conservador (mediana): {np.median(distancias_k):.2f}")
    print(f"- Epsilon permisivo (percentil 95): {np.percentile(distancias_k, 95):.2f}")

    return np.median(distancias_k), np.percentile(distancias_k, 95)

# Ejecutar diagnóstico
columnas_dbscan = ['Edad', 'Ingreso', 'Puntaje_Credito', 'Monto_Deuda', 'Tasa_Interes']
eps_mediana, eps_p95 = encontrar_epsilon_optimo(dataset, columnas_dbscan, k=5)

# PROBAR MÚLTIPLES COMBINACIONES
print("\n" + "="*60)
print("PROBANDO DIFERENTES PARÁMETROS")
print("="*60)

parametros_probar = [
    (eps_mediana, 3),
    (eps_mediana, 5),
    (eps_p95, 3),
    (eps_p95, 5),
    (eps_p95, 10)
]

for eps, min_samp in parametros_probar:
    print(f"\n>>> Probando epsilon={eps:.2f}, min_samples={min_samp}")
    dataset_test = detectar_outlier_dbscan(dataset, columnas_dbscan, epsilon=eps, min_samples=min_samp)
    print()

# Paso 1: Definir las columnas a utilizar
columnas_dbscan = ['Edad', 'Ingreso', 'Puntaje_Credito', 'Monto_Deuda', 'Tasa_Interes']

# Paso 2: Detectar Outlier con DBSCAN (PARÁMETROS OPTIMIZADOS)
dataset_dbscan = detectar_outlier_dbscan(
    dataset,
    columnas=columnas_dbscan,
    epsilon=0.92,      # Usar el percentil 95
    min_samples=3      # Valor estándar
)

# Paso 3: Visualizar los outliers
graficar_outliers_dbscan(dataset_dbscan, columnas_dbscan)

# Paso 4: Filtrar registros normales
dataset_limpio_dbscan = eliminar_outliers_dbscan(dataset_dbscan, outlier_col='cluster', conservar_columna=False)

"""# **Sección 3: Detección de Valores Atípicos**

## 3.2	Método Multivariante   

---

3.2.3 *Método del Factor Atipico Local (LOF)*

"""

# Buscamos DETECTAR los Outliers

from sklearn.neighbors import LocalOutlierFactor

def detectar_outlier_LOF(dataset, columnas, n_neighbors=20, contamination='auto'):
    """
    Detectar outliers usando Local Outlier Factor en múltiples columnas

    Parámetros:
    - dataset: DataFrame
    - columnas: lista de columnas a analizar
    - n_neighbors: número de vecinos a considerar (default 20)
    - contamination: proporción esperada de outliers ('auto' o valor entre 0 y 0.5)

    Retorna:
    - DataFrame con columnas 'LOF_outlier' (1=normal, -1=outlier) y 'LOF_score'
    """
    datos = dataset.copy()

    # Filtrar datos válidos (sin NaN)
    datos_validos = datos[columnas].dropna()

    if len(datos_validos) == 0:
        print("No hay datos válidos para analizar")
        return datos

    # Escalar los datos
    X = datos_validos.values
    X_scaled = StandardScaler().fit_transform(X)

    # Aplicar LOF
    lof = LocalOutlierFactor(n_neighbors=n_neighbors, contamination=contamination)
    etiquetas = lof.fit_predict(X_scaled)  # 1 = normal, -1 = outlier
    scores = lof.negative_outlier_factor_

    # Inicializar columnas con NaN
    datos['LOF_outlier'] = np.nan
    datos['LOF_score'] = np.nan

    # Asignar valores solo a filas válidas
    datos.loc[datos_validos.index, 'LOF_outlier'] = etiquetas
    datos.loc[datos_validos.index, 'LOF_score'] = scores

    # Estadísticas
    n_outliers = (etiquetas == -1).sum()
    n_normales = (etiquetas == 1).sum()
    print(f"Outliers detectados: {n_outliers} ({n_outliers/len(etiquetas)*100:.2f}%)")
    print(f"Puntos normales: {n_normales} ({n_normales/len(etiquetas)*100:.2f}%)")

    return datos

# Buscamos GRAFICAR

def graficar_outliers_LOF(dataset, columnas, outlier_col='LOF_outlier'):
    """
    Visualizar outliers vs normales detectados por LOF.
    Si hay más de 2 columnas, se aplica PCA para reducir a 2D.
    """
    if len(columnas) < 2:
        raise ValueError("Se necesitan al menos 2 columnas para graficar")

    # Filtrar datos válidos
    columnas_analizar = columnas + [outlier_col]
    datos_validos = dataset[columnas_analizar].dropna()

    if len(datos_validos) == 0:
        print("No hay datos válidos para graficar")
        return

    # Reducción con PCA si hay más de 2 columnas
    if len(columnas) > 2:
        print('Aplicando PCA para reducir las dimensiones...')
        X = datos_validos[columnas].values
        X_reducido = PCA(n_components=2, random_state=123).fit_transform(X)
        x_label, y_label = "PCA Componente 1", "PCA Componente 2"
    else:
        X_reducido = datos_validos[columnas].values
        x_label, y_label = columnas[0], columnas[1]

    # Obtener etiquetas
    etiquetas = datos_validos[outlier_col].values
    normales = etiquetas == 1
    outliers = etiquetas == -1

    # Crear la figura
    plt.figure(figsize=(10, 6))

    # Graficar puntos normales
    plt.scatter(X_reducido[normales, 0], X_reducido[normales, 1],
                color='blue', label='Puntos Normales',
                edgecolor='black', alpha=0.7, s=60)

    # Graficar outliers
    plt.scatter(X_reducido[outliers, 0], X_reducido[outliers, 1],
                color='red', label='Puntos Outliers',
                edgecolor='black', alpha=0.7, s=60)

    # Etiquetas y leyenda
    plt.xlabel(x_label)
    plt.ylabel(y_label)
    plt.legend(loc='upper right')
    plt.title('Visualización de Outliers con LOF (Local Outlier Factor)')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

# Ahora buscamos ELIMINAR los outliers

def eliminar_outliers_LOF(dataset, outlier_col='LOF_outlier', conservar_columna=False):
    """
    Elimina los outliers detectados por LOF (etiqueta -1)

    Parámetros:
    - dataset: DataFrame con columna de outliers LOF
    - outlier_col: nombre de la columna con etiquetas (default 'LOF_outlier')
    - conservar_columna: si True, mantiene las columnas LOF

    Retorna:
    - DataFrame sin outliers
    """
    # Filtrar filas que NO son outliers
    df_resultado = dataset[dataset[outlier_col] != -1].copy()

    # Eliminar columnas LOF si se solicita
    if not conservar_columna:
        columnas_eliminar = [c for c in ['LOF_outlier', 'LOF_score'] if c in df_resultado.columns]
        df_resultado = df_resultado.drop(columns=columnas_eliminar)

    # Estadísticas
    n_eliminados = len(dataset) - len(df_resultado)
    print(f'\nFilas originales: {len(dataset)}')
    print(f'Outliers eliminados: {n_eliminados} ({n_eliminados/len(dataset)*100:.2f}%)')
    print(f'Filas restantes: {len(df_resultado)}')

    return df_resultado

# Aplicamos los pasos para Graficar

# Paso 1: Definir las columnas a utilizar
columnas_lof = ['Edad', 'Ingreso', 'Puntaje_Credito', 'Monto_Deuda', 'Tasa_Interes']

# Paso 2: Detectar Outliers con LOF
dataset_lof = detectar_outlier_LOF(
    dataset,
    columnas=columnas_lof,
    n_neighbors=20,        # Número de vecinos (prueba entre 10-30)
    contamination=0.05     # 5% de outliers esperados (o usa 'auto')
)

# Paso 3: Visualizar los outliers
graficar_outliers_LOF(dataset_lof, columnas_lof)

# Paso 4: Eliminar outliers
dataset_limpio_lof = eliminar_outliers_LOF(
    dataset_lof,
    outlier_col='LOF_outlier',
    conservar_columna=False
)

# Trabajamos la data numerica para la Matriz de Correlacion con nuestro dataset

corr = dataset.corr(numeric_only= True)

print(corr)

# Graficamos un "Mapa de Calor" con la data

fig, ax  =  plt.subplots(figsize = (15,10))
sns.heatmap(corr, annot = True,cmap = 'YlGnBu', ax = ax, vmax = 1, vmin = -1)
plt.title('Matriz de Correlacion')
plt.show()

"""# **Sección 4: Correlación entre los Datoss**

## 4.2	Graficas de correlación; 1 x 1 en base al Monto_Deuda
"""

# Graficamos la correlación entre Edad y Monto Deuda

plt.figure(figsize=(12, 6))
sns.regplot(data=dataset, x='Edad', y='Monto_Deuda', scatter_kws={'alpha':0.7}, line_kws={'color':'red'})

plt.xlabel('Edad')
plt.ylabel('Monto de Deuda')
plt.title('Relación entre la Edad y el Monto de Deuda', fontsize=14, fontweight='bold')
plt.grid(True)

plt.show()

# Graficamos la correlación entre Ingreso y Monto Deuda


plt.figure(figsize=(12, 6))
sns.regplot(data=dataset, x='Ingreso', y='Monto_Deuda', scatter_kws={'alpha':0.7}, line_kws={'color':'red'})

plt.xlabel('Ingreso')
plt.ylabel('Monto de Deuda')
plt.title('Relación entre el Ingreso y el Monto de Deuda', fontsize=14, fontweight='bold')
plt.grid(True)

plt.show()

# Graficamos la correlación entre Puntaje_Crédito y Monto Deuda


plt.figure(figsize=(12, 6))
sns.regplot(data=dataset, x='Puntaje_Credito', y='Monto_Deuda', scatter_kws={'alpha':0.7}, line_kws={'color':'red'})

plt.xlabel('Puntaje de Crédito')
plt.ylabel('Monto de Deuda')
plt.title('Relación entre el Puntaje de Crédito y el Monto de Deuda', fontsize=14, fontweight='bold')
plt.grid(True)

plt.show()

# Graficamos la correlación entre Tasa_Interes y Monto Deuda


plt.figure(figsize=(12, 6))
sns.regplot(data=dataset, x='Tasa_Interes', y='Monto_Deuda', scatter_kws={'alpha':0.7}, line_kws={'color':'red'})

plt.xlabel('Tasa de Interés (%)')
plt.ylabel('Monto de Deuda')
plt.title('Relación entre la Tasa de Interés y el Monto de Deuda', fontsize=14, fontweight='bold')
plt.grid(True)

plt.show()

"""# **Sección 5: Conclusiones Finales**

# **Resumen de los hallazgos**

### **1. CALIDAD Y ESTRUCTURA DE LOS DATOS**
Tamaño del dataset: 1,000 registros × 5 variables numéricas
Datos faltantes: 100 registros (10%) con valores NaN - una proporción considerable que puede afectar el análisis
Datos válidos: 900 registros completos disponibles para análisis
Variables analizadas: Edad, Ingreso, Puntaje_Credito, Monto_Deuda, Tasa_Interes (traducidas del inglés)

### **2. ESTADÍSTICAS DESCRIPTIVAS DETALLADAS**
**Edad:**

Promedio: 41 años | Desviación: 13.6 años
Rango: 18-64 años (población adulta activa)
Distribución balanceada entre jóvenes, adultos y seniors

**Ingreso:**

Promedio: $75,151 | Mediana: $74,985
Gran dispersión (desviación: $25,866)
Rango: $30,060 - $119,899
Distribución relativamente normal, sin concentración extrema

**Puntaje de Crédito:**

Promedio: 583 | Mediana: 585
Desviación: 155.8 puntos (muy variable)
Rango: 300-849 (casi todo el espectro posible)
La mediana cerca del promedio sugiere distribución simétrica

**Monto de Deuda:**

Promedio: $27,396 | Mediana: $27,054
Rango: $5,112 - $49,864
Distribución amplia pero sin valores extremos obvios
Q1: $17,038 | Q3: $37,792

**Tasa de Interés:**

Promedio: 8.96% | Mediana: 8.91%
Rango: 3.02% - 14.97%
Bastante dispersión (desviación: 3.4%)


### **3. ANÁLISIS DE CORRELACIONES (Pearson)**
**Hallazgo Principal: No hay correlaciones significativas**

Todas las correlaciones entre variables son menores a 0.05 (umbral de relevancia mínima):

Edad vs Monto_Deuda: -0.042 (casi nula, ligeramente negativa)
Ingreso vs Monto_Deuda: -0.038 (casi nula)
Puntaje_Credito vs Monto_Deuda: 0.032 (casi nula)
Edad vs Ingreso: 0.006 (prácticamente cero)
Puntaje_Credito vs Tasa_Interes: 0.014 (casi nula)

**Implicaciones:**

Las variables son independientes entre sí
Tener más edad NO predice mayor o menor deuda
Ganar más dinero NO garantiza mejor puntaje de crédito
El puntaje de crédito NO afecta significativamente la tasa de interés (sorprendente)
Esto sugiere que hay otros factores no capturados en el dataset


### **4. DETECCIÓN DE OUTLIERS - COMPARACIÓN DE MÉTODOS**
Para El análisis aplicó CUATRO métodos diferentes de detección de outliers:

**A) Isolation Forest (Multivariante)**

Outliers detectados: 191 (19.1% del dataset)
Dataset limpio: 809 registros
Características: Método más agresivo, detecta anomalías globales
Interpretación: Casi 1 de cada 5 registros tiene patrones inusuales

**B) DBSCAN (Clustering)**

Outliers detectados: 65 (6.5%)
Dataset limpio: 935 registros
Clusters encontrados: 6-9 grupos naturales
Parámetros óptimos: epsilon=0.92, min_samples=3
Interpretación: Identifica puntos que no pertenecen a ningún cluster denso

**C) LOF - Local Outlier Factor (Multivariante)**

Outliers detectados: 45 (4.5%)
Dataset limpio: 955 registros
Características: Método más conservador, evalúa anomalías locales
Interpretación: Solo los casos más extremos son marcados

**D) Método IQR (Univariante - Monto_Deuda)**

Límite superior: $68,924

Límite inferior: -$14,094 (no aplicable, teórico)

Q1: $17,038 | Q3: $37,792 | IQR: $20,755

Interpretación: Deudas superiores a $69K son atípicamente altas


### **5. VISUALIZACIONES GENERADAS**

El análisis incluyó múltiples visualizaciones:

- **Histogramas con curvas normales:** Para cada variable (Edad, Ingreso, Puntaje_Credito, Monto_Deuda, Tasa_Interes)
- **Matriz de correlación (heatmap):** Confirmó visualmente las bajas correlaciones
- **Pairplots categorizados:** Con segmentación por Ingreso, Edad, Puntaje_Credito, Monto_Deuda, Tasa_Interes
- **Gráficos de outliers IQR:** Mostrando zonas rojas de valores atípicos
- **Scatter plots de outliers:** Para Isolation Forest, DBSCAN y LOF con PCA
- **Gráficos de dispersión:** Relaciones entre Monto_Deuda vs Edad, Ingreso, Puntaje_Credito, Tasa_Interes.


### **6. LOS HALLAZGOS CLAVE**


### **Hallazgos:**

Alto porcentaje de datos completos (90%) - dataset confiable
Variables independientes - no hay multicolinealidad, bueno para modelos
Distribuciones relativamente normales - apropiado para análisis paramétricos
Variabilidad considerable - sugiere diversidad en la población
Diferentes métodos detectan diferentes outliers - no hay consenso absoluto

### **Recomendaciones:**

**Para hacer modelado predictivo:**
- Puede usarse el método LOF (más conservador) para mantener más datos (955 registros)
- Permite conservar máxima información útil

**Para buscar patrones limpios:**
- Puede usarse DBSCAN (término medio) para balancear limpieza y tamaño (935 registros)
- Identifica clusters naturales

**Para lograr una máxima calidad:**
- Puede emplearse la técnica del Bosque de Aislamiento (más estricto) para datos ultra-limpios (809 registros)
- Sacrifica cantidad por pureza.

**Para realizar reportes ejecutivos:**
- Las correlaciones nulas sugieren que cada variable aporta información única.
- Los outliers representan casos especiales que merecen investigación individual.


### **Limitaciones detectadas:**

- Solo  tenemos 5   variables - pueden existir factores ocultos
- 10% de datos faltantes sin análisis de patrón de pérdida
- No hay variables categóricas (género, región, tipo de préstamo, etc.)
- Falta análisis temporal si los datos tienen fecha

### **Próximos pasos sugeridos:**

- Investigar por qué hay outliers (¿fraude?, ¿errores?, ¿casos legítimos especiales?)
- Analizar el patrón de datos faltantes (¿aleatorios o sistemáticos?)
- Considerar técnicas de imputación para los NaN
- Explorar modelos de machine learning (regresión, clasificación)
-  Segmeentar la población en perfiles de riesgo
"""